name: Lint and Format

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy

      - name: Run ruff (lint)
        run: ruff check . --output-format=github

      - name: Run black (check formatting)
        run: black --check .

      - name: Run mypy (type checking)
        run: mypy scanner.py test_scanner.py

